# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"
theme = ["hugo-notice", "blowfish", "hugo-shortcode-gallery", "gpx-shortcode", "osm"]
baseURL = "https://hiketheministik.ca"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true

[pagination]
  pagerSize = 100

summaryLength = 0 # A value of 0 will use the first sentence.

buildDrafts = false
buildFuture = false

enableEmoji = true
# Commented this out on July 27 after having set up GoatCounter instead.
# I found Google Analytics to be ridiculously convuluted and complicated, hence the change
# once I discovered https://www.goatcounter.com/ via setting up Quartz 4
# googleAnalytics = "G-Z5BW9M8VGL"

# Raise generation timeout from 10s to 60s to account for our heavy image
# processing when rendering the site from scratch.
timeout = 60000

[imaging]
  anchor = 'Center'
# This line below is to allow the hugo-shortcode-gallery to display exif data in lightbox
# I found that the gallery code will only display JPG exif data, not webp exif.
[imaging.exif]
  includeFields = ".*"
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
