# -- Markup --
# These settings are required for the theme to function.
[tableOfContents]
  startLevel = 2
  endLevel = 4

[goldmark]
[goldmark.renderer]
  unsafe = true
# inserted this because of a "correct" answer to the question about how to center
# images from https://discourse.gohugo.io/t/center-an-image/47549/3
# then to center image: ![my_image](my_image_address) {.please-center}
# BUT THIS DOESN'T WORK

[goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
[goldmark.parser.attribute]
  block = true
[highlight]
  noClasses = false
